---
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
    md_extensions: +yaml_metadata_block
    template: cv_template.tex
---

---
person:
  first_name: Arturo
  last_name: Cárdenas Martínez
  postnoms:
  title:
  headline: Data Scientist / Retail / Supply Chain Professional
---

---
aside:
  - section: contacto \FA \faUser
    content: |
      234 Alejandro Magno Monterrey, NL 64610 Mexico
  - item: tel
    content: |
    	\makebox {+52 1 (662) 363 2356 \FA \faPhone}
  - item: links
    content: |
      \makebox{\href{mailto:arturo.cardenas@mail.mcgill.ca}{\footnotesize arturo.cardenas@mail.mcgill.ca {\FA \faEnvelope}}}
      \href{mailto:arturocam@gmail.com.com}{arturocam@gmail.com {\FA \faEnvelopeAlt}}
      \href{https://github.com/arturocm/}{arturocm {\FA \faGithub}}
      \href{http://arturocm.github.io/}{arturocm.github.io {\FA \faExternalLink}}
      \href{http://arturocm.github.io/}{arturocm.github.io {\FA \faExternalLink}}
      \href{https://www.linkedin.com/in/arturocardenas}{arturocardenas {\FA \faLinkedin}}
      \href{http://twitter.com/arturocm}{arturocm {\FA \faTwitter}}  
  - section: skills \FA \faTachometer
    content: |
      \makebox{Supply Chain}
      \makebox{Machine Learning}
      \makebox{Visualización de Datos}
      \makebox{Business Intelligence}
      \makebox{Business Modelling}
      \makebox{Investigación Operaciones}
      \makebox{Mejora Continua}
      \makebox{Forecasting}
      \makebox{Mejora de Procesos}
      \makebox{Suministro}
      \makebox{Operacion de Tiendas}
      \makebox{Dinámica de Sistemas}
      \makebox{Optimización de Sistemas}
  - section: certificaciones \FA \faCertificate
    content: |
    	\makebox {Six Sigma Green Belt \FA \faCheckNice}
    	\makebox {Lean Project Leader \FA \faCheckNice}
    	\makebox {Data Scientist Spec. \FA \faCheckNice}
  - section: idiomas \FA \faLanguage
    content: |
    	\makebox {Español \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faDotCircle}
    	\makebox {Inglés \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faDotCircle}
  - section: programación \FA \faCode
    content: |
     \makebox {R \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faCircleO}
      \makebox {SQL \FA \faDotCircle \FA \faDotCircle \FA \faDotCircle \FA \faDotCircle \FA \faCircleO}
      \makebox {Visual Basic \FA \faDotCircle \faDotCircle \faDotCircle \faCircleO \faCircleO}
      \makebox {Python \FA \faDotCircle \faDotCircle \faCircleO \faCircleO \faCircleO}
      \makebox {\LaTeX \_ \FA \faDotCircle \faCircleO \faCircleO \faCircleO \faCircleO}
      \makebox {HTML \FA \faDotCircle \faCircleO \faCircleO \faCircleO \faCircleO}
      \makebox {Java \FA \faDotCircle \faDotCircle \faCircleO \faCircleO \faCircleO}
  - section: software \FA \faLaptop
    content: |
      \makebox {KNIME \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faDotCircle}
      \makebox {Shiny Apps \FA \faDotCircle \faDotCircle \faDotCircle \faCircleO \faCircleO}
      \makebox {MS Access \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faCircleO}
      \makebox {MS Excel \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faDotCircle}
      \makebox {MS Visio \FA \faDotCircle \faDotCircle \faDotCircle \faCircleO \faCircleO}
      \makebox {Vensim \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faCircleO}
      \makebox {Solver \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faDotCircle}
      \makebox {Nielsen \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faCircleO}
      \makebox {Retail Link \FA \faDotCircle \faDotCircle \faDotCircle \faDotCircle \faCircleO}
      \makebox {TIBCO Spotfire \FA \faDotCircle \faDotCircle \faDotCircle \faCircleO \faCircleO}
---

---
main:
  - section: Experiencia \FA \faBriefcase  
  - entrylist:
  
      - when: 2016
        what: Data Scientist
        who: Freelancer
        where: Monterrey, Mexico
        desc: |
          •	Desarollo de modelos predictivos y productos de data aplicando analíticos avanzados

      - when: 2015 2014
        what: Retail Data Analytics Specialist
        who: Procter \& Gamble - Walmart Canada Team
        where: Toronto, Canada
        desc: |
          •	Creación y desarrollo de proceso desruptivo de extracción, transformación y carga (ETL) para POS data Nacional. Reducción del Acuerdo de Nivel de Servicio (SLA) de 20 a 3 días lo cual habilitó a los equipos de ventas a vender con "más, mejor y veloz" data. Solamente en Walmart Canada resultó en la obtención de la capitancía en las categorias de Oral Care, Fem Care y Baby Care representando un incremento de POS de **~$5million** anuales  
          •	Diseño de análisis de regresión de co-dependencia de marcas en eventos  para maximizar ROI en eventos y promociones al igual que incrementar Market Share  
          •	Responsable de entrenamiento global en KNIME para el area de Analíticos Avanzados  
          •	Visualización del impacto de marcas privadas en Walmat Canada por medio de Spotfire  
          •	Elaboración de propuesta para untilizar Hadoop para mejorar el proceso de ETL de POS data por medio de Sqoop y Hive  
        
      - when: 2014 2013
        what: Retail Replenishment Analyst
        who: Procter \& Gamble - Walmart Canada Team
        where: Toronto, Canada
        desc: |
          •	Responsable de reaprovisionamiento de las categorias de Salud y Belleza, con un valor anual en ventas de **$250million** anuales  
          •	Generación de ***$5.8million*** en ventas impulsadas por medio de Supply Chain gracias al uso de analíticos e intervenciones de reaprovisionamiento   
          •	Creación y desarrollo de projecto piloto "How high is up" para mejorar forecasts y reducir inventarios. Esto generó un crecimiento de 4% en POS de Fem Care (***$2million***) y de 4% en POS de Shaving (***$1million***) en un periodo de 4 meses    
          •	Delivered time savings of ***120 man hours*** per month by redesigning and automating forecast and replenishment processes that impact across P&G’s entire portfolio at Walmart  
          •	Increased P&G’s product portfolio in-stock (***+1% VYA***) by revamping replenishment weekly in-stock reporting allowing eleven team members to readily ID opportunities, root causes and drive to resolution faster  
          •	Streamlined customer service coverage for largest P&G scale event in N America delivering 100 hours staffing requirement decrease and 100% reported data integrity (***+10% VYA***).  
          
      - when: 2013
        what: On-Shelf Availability Analyst
        who: Procter \& Gamble - Walmart Canada Team
        where: Toronto, Canada
        desc: |
          
          •	Identified phantom inventory instances by developing a dashboard based on POS data
          
      - when: 2012
        what: Supply Chain Consultant
        who: Future Electronics Inc.
        where: Montreal, Canada
        desc: |
          •	Achieved 10% savings in transportation costs (***$120,000***) by segmenting shipping methods
          
      - when: 2011
        what: Supply Chain System Dynamics Analyst (Independent Study) 
        who: Bombardier Aerospace
        where: Montreal, Canada
        desc: |
          •	Identified key factors disturbing the system model and simulated alternative policies to improve overall performance  
          •	Co-wrote paper presented and published at the 30th International Conference of the System Dynamics Society: [Industry Analysis: The Fastener Supply Chain in Aerospace Industry](http://www.systemdynamics.org/conferences/2012/proceed/papers/P1296.pdf)  

      - when: 2010 2006
        what: Supply Services Manager
        who: IECOS
        where: Monterrey, Mexico
        desc: |
          •	Increased 300% monthly revenues (***$10,000***) by implementing new replenishment program 
        
  - section: Education \FA \faGraduation   
  
  - entrylist:
      - who: McGill University
        where: Montreal, Canada
        what: Master Manufacturing Management
        when: 2012 2010
        desc: |
          Specialization in Supply Chain and Global Operations
          
      - who: ITESM Campus Monterrey
        where: Monterrey, Mexico
        what: Bachelor of Science in Mechanical Engineering
        when: 2006 2000
        desc: |
        	Minor in Industrial Engineering 
        	
  - section: Honors and Awards \FA \faTrophy
  
---

•	P&G’s “Execute with Excellence” Pearl Award for groundbreaking results in Fem Care pilot project  
•	McGill MMM program performance scholarship, awarded to top students during the Fall 2010    